apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: sysctl-inotify
  namespace: kube-system
  labels:
    app: sysctl-inotify
spec:
  selector:
    matchLabels:
      app: sysctl-inotify
  template:
    metadata:
      labels:
        app: sysctl-inotify
    spec:
      hostPID: true 
      containers:
        - name: sysctl
          image: busybox:1.36
          securityContext:
            privileged: true
          command:
            - sh
            - -c
            - |
              echo "Ajustando sysctl inotify..."
              sysctl -w fs.inotify.max_user_watches=524288
              sysctl -w fs.inotify.max_user_instances=512
              # mantém pod vivo para DaemonSet não morrer
              tail -f /dev/null
